project_id = "ineajuhvkfdpvtzattfe"

[functions.voice-to-text]
verify_jwt = true

[functions.analyze-sentiment]
verify_jwt = true

[functions.analyze-medication-label]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = true

[functions.text-to-speech-eleven]
verify_jwt = true

[functions.realtime-token]
verify_jwt = true

[functions.backfill-highlights]
verify_jwt = true

[functions.backfill-audio-summaries]
verify_jwt = true

[functions.generate-audio-summary]
verify_jwt = true