// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/list-check-ins.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-check-ins.ts
var list_check_ins_default = defineTool({
  name: "list_check_ins",
  title: "List check-ins",
  description: "List the signed-in user's recent wellness check-ins with mood, sentiment and health scores.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many check-ins to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("check_ins").select(
      "id, created_at, mood_rating, sleep_quality, pain_level, sentiment_label, sentiment_score, overall_score, physical_health_score, mental_health_score, highlights, concerns"
    ).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { check_ins: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-check-in.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var get_check_in_default = defineTool2({
  name: "get_check_in",
  title: "Get check-in detail",
  description: "Get one of the signed-in user's check-ins in full, including the conversation transcript and summary.",
  inputSchema: {
    check_in_id: z2.string().uuid().describe("The id of the check-in to fetch.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ check_in_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("check_ins").select(
      "id, created_at, transcript, notes, audio_summary_text, mood_rating, sleep_quality, pain_level, sentiment_label, sentiment_score, overall_score, physical_health_score, mental_health_score, emotions, highlights, concerns, physical_indicators, mental_indicators"
    ).eq("id", check_in_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No check-in found with that id." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { check_in: data }
    };
  }
});

// src/lib/mcp/tools/list-medications.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var list_medications_default = defineTool3({
  name: "list_medications",
  title: "List medications",
  description: "List the signed-in user's medications with dosage, frequency and schedule.",
  inputSchema: {
    include_inactive: z3.boolean().default(false).describe("Include medications that are no longer active.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_inactive }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("medications").select("id, name, dosage, frequency, time_of_day, instructions, active").order("name", { ascending: true });
    if (!include_inactive) query = query.eq("active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { medications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-medication.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var log_medication_default = defineTool4({
  name: "log_medication",
  title: "Log a medication dose",
  description: "Record whether the signed-in user took one of their medications. The medication must belong to them.",
  inputSchema: {
    medication_id: z4.string().uuid().describe("The id of the medication, from list_medications."),
    was_taken: z4.boolean().describe("True if the dose was taken, false if it was missed."),
    notes: z4.string().trim().max(500).optional().describe("Optional note about this dose.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ medication_id, was_taken, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: med, error: medError } = await supabase.from("medications").select("id, name").eq("id", medication_id).maybeSingle();
    if (medError) return { content: [{ type: "text", text: medError.message }], isError: true };
    if (!med) {
      return {
        content: [{ type: "text", text: "That medication was not found for this user." }],
        isError: true
      };
    }
    const { data, error } = await supabase.from("medication_logs").insert({
      user_id: ctx.getUserId(),
      medication_id,
      was_taken,
      notes: notes ?? null
    }).select("id, medication_id, was_taken, taken_at, notes").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        {
          type: "text",
          text: `Logged ${med.name} as ${was_taken ? "taken" : "not taken"}.`
        }
      ],
      structuredContent: { log: data }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.0.4";
var get_profile_default = defineTool5({
  name: "get_profile",
  title: "Get profile",
  description: "Get the signed-in user's profile: name and the physical and mental health context they recorded.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("full_name, phone, physical_health_issues, mental_health_issues, created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No profile found for this user." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ineajuhvkfdpvtzattfe";
var mcp_default = defineMcp({
  name: "cheqin",
  title: "cheqin",
  version: "0.1.0",
  instructions: "Tools for cheqin, a wellness check-in app for seniors. Every tool acts as the signed-in user: read their recent check-ins and transcripts, their profile and health context, their medications, and log medication doses. Never infer medications or conditions that these tools do not return.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    list_check_ins_default,
    get_check_in_default,
    list_medications_default,
    log_medication_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
