-- Add audio summary fields to check_ins and storage bucket for audio files
-- Create columns if not exist
ALTER TABLE public.check_ins 
  ADD COLUMN IF NOT EXISTS audio_summary_url TEXT,
  ADD COLUMN IF NOT EXISTS audio_summary_text TEXT,
  ADD COLUMN IF NOT EXISTS audio_summary_generated_at TIMESTAMPTZ;

-- Optional index for faster queries by generation time
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relname = 'idx_check_ins_audio_generated_at'
      AND n.nspname = 'public'
  ) THEN
    CREATE INDEX idx_check_ins_audio_generated_at 
      ON public.check_ins(audio_summary_generated_at DESC);
  END IF;
END $$;

-- Create storage bucket for audio summaries (private)
INSERT INTO storage.buckets (id, name, public)
VALUES ('audio-summaries', 'audio-summaries', false)
ON CONFLICT (id) DO NOTHING;

-- Note: We will access files via signed URLs generated by backend functions.
